config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :short_urls
  devise_for :users
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
  acts_as_tenant :account

  validates_presence_of :mini_url, :original_url

  before_validation :build_mini_url

  def formatted_original_url
    url = URI.parse(original_url)
    if url.scheme.present?
      original_url
    else
      'http://' + url.path
    end
  end

  private

    def build_mini_url
      loop do
        self.mini_url = SecureRandom.hex(3)
        break if ShortUrl.where(mini_url: self.mini_url).empty?
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :account

  before_validation :set_account
              
  def set_account
      self.build_account
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
  set_current_tenant_through_filter
  before_action :set_current_account

  def set_current_account
    return unless current_user.present?
    current_account = current_user.account
    ActsAsTenant.current_tenant = current_account
  end

    def after_sign_in_path_for(resource)
        short_urls_url
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_short_url, only: %i[ show edit update destroy ]


  # GET /short_urls or /short_urls.json
  def index
    @short_urls = ShortUrl.all
    @short_url = ShortUrl.new
  end

  # GET /short_urls/1 or /short_urls/1.json
  def show
  end

  # GET /short_urls/new
  def new
    @short_url = ShortUrl.new
  end

  # GET /short_urls/1/edit
  def edit
  end

  # POST /short_urls or /short_urls.json
  def create
    @short_url = ShortUrl.new(short_url_params)

    respond_to do |format|
      if @short_url.save
        format.html { redirect_to "https://peteris-url-app.herokuapp.com/short_urls", notice: "Short url was successfully created." }
        format.json { render :show, status: :created, location: @short_url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @short_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /short_urls/1 or /short_urls/1.json
  def update
    respond_to do |format|
      if @short_url.update(short_url_params)
        format.html { redirect_to @short_url, notice: "Short url was successfully updated." }
        format.json { render :show, status: :ok, location: @short_url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @short_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /short_urls/1 or /short_urls/1.json
  def destroy
    @short_url.destroy
    respond_to do |format|
      format.html { redirect_to short_urls_url, notice: "Short url was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_short_url
      @short_url = ShortUrl.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def short_url_params
      params.require(:short_url).permit(:mini_url, :original_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
        :user
      end
    
      def resource
        @resource ||= User.new
      end
    
      def resource_class
        User
      end
    
      def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
      end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeterisUrlAppV1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" 
      integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid p-0">
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
  <h1 class="display-4">Place for ...</h1>
  <p class="lead">This is a simple place where you can store and shorten your favorit links</p>
  <hr class="my-4">
  <p>Sign Up to day and keep your browser cleen !!!</p>
  <p class="lead">
    <a class="btn btn-primary btn-small" href="/users/sign_up" role="button">Sign Up</a>
  </p>
</div>
<div class="row justify-content-center">
    <%= render 'shared/login' %>
</div>

app/views/shared/_flash_messages.html.erb
<% if flash.count > 0 %>
  <div class="flash-messages-container">
    <% flash.each do |flash_type, msg| %>
      <div class="alert alert-dismissible fade show" role="alert">
        <p class="flash-body mb-1"><%= msg.html_safe %></p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>Shorter Urls. <%= Time.now.year %></p>
</div>

app/views/shared/_login.html.erb
<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title text-center">Log in</h5>
        <div class="form-group text-center">
            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                <div class="field">
                    <label for="exampleInputEmail1">Email address</label>
                    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
                </div>

                <div class="field">
                    <label for="exampleInputPassword1">Password</label>
                    <%= f.password_field :password, autocomplete: "current-password", class: "form-control mx-sm-10"  %>
                </div>

                <% if devise_mapping.rememberable? %>
                    <div class="field">
                        <%= f.check_box :remember_me %>
                        <%= f.label :remember_me %>
                    </div>
                <% end %>

                <div class="actions">
                    <%= f.submit "Log in", class: "btn btn-primary" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Your-Urls</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
    </div>
    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% end %>
    </p>
  </div>
</nav>

app/views/short_urls/_form.html.erb
<%= form_with(model: @short_url) do |form| %>
  <% if @short_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(short_url.errors.count, "error") %> prohibited this short_url from being saved:</h2>

      <ul>
        <% short_url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <%= form.submit class: 'btn btn-outline-secondary' %>
    </div>
    <%= form.text_field :original_url, class: 'form-control' %>
  </div>

<% end %>

app/views/short_urls/edit.html.erb
<h1>Editing Short Url</h1>

<%= render 'form', short_url: @short_url %>

<%= link_to 'Show', @short_url %> |
<%= link_to 'Back', short_urls_path %>

app/views/short_urls/index.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron text-center">
  <h1 class="display-5">Short Url List</h1>
  <p class="lead">Copy and paste your link and magic will appear</p>
  <hr class="my-4">
  <p>Create and save your favorit links up to 100!!!</p>
  <div class='container'>
    <%= render 'short_urls/form' %>
  </div>
  <hr class="my-4">
</div>
<div class="container">
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Short url</th>
      <th>Original url</th>
      <th colspan="3">Option</th>
    </tr>
  </thead>

  <tbody>
    <% @short_urls.each do |short_url| %>
      <tr>
        <td><a href='<%= short_url.original_url %>' target='blank'><%= root_url %><%= short_url.mini_url %></a></td>
        <td><a href='<%= short_url.original_url %>' target='blank'><%= short_url.original_url %></a></td>
        <td><%= link_to 'Destroy', short_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/short_urls/new.html.erb
<h1>New Short Url</h1>

<%= render 'form', short_url: @short_url %>

<%= link_to 'Back', short_urls_path %>

app/views/short_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mini url:</strong>
  <%= @short_url.mini_url %>
</p>

<p>
  <strong>Original url:</strong>
  <%= @short_url.original_url %>
</p>

<%= link_to 'Edit', edit_short_url_path(@short_url) %> |
<%= link_to 'Back', short_urls_path %>